class exception {

	public static void main (String args[])
	{
		try
		{
			int data=50/0;
			System.out.println(data);
			
	     }
		catch(NullPointerException e)
		{
			System.out.println(e);
		}
	
finally

	{
		System.out.println("finally block is executed here");
	}
	
	System.out.println("rest is the code here");
	}
}
